/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVmsRouteImport } from './routes/app.vms'
import { Route as AppConsoleRouteImport } from './routes/app.console'
import { Route as AppClustersRouteImport } from './routes/app.clusters'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminQuotaRouteImport } from './routes/app.admin.quota'
import { Route as AppAdminNetworksRouteImport } from './routes/app.admin.networks'
import { Route as AppAdminClusterOfferingsRouteImport } from './routes/app.admin.cluster-offerings'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVmsRoute = AppVmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleRoute = AppConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersRoute = AppClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQuotaRoute = AppAdminQuotaRouteImport.update({
  id: '/admin/quota',
  path: '/admin/quota',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNetworksRoute = AppAdminNetworksRouteImport.update({
  id: '/admin/networks',
  path: '/admin/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClusterOfferingsRoute =
  AppAdminClusterOfferingsRouteImport.update({
    id: '/admin/cluster-offerings',
    path: '/admin/cluster-offerings',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRoute
  '/app/console': typeof AppConsoleRoute
  '/app/vms': typeof AppVmsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRoute
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRoute
  '/app/console': typeof AppConsoleRoute
  '/app/vms': typeof AppVmsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRoute
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRoute
  '/app/console': typeof AppConsoleRoute
  '/app/vms': typeof AppVmsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRoute
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/activity'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/vms'
    | '/app/'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/activity'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/vms'
    | '/app'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/activity'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/vms'
    | '/app/'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vms': {
      id: '/app/vms'
      path: '/vms'
      fullPath: '/app/vms'
      preLoaderRoute: typeof AppVmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/console': {
      id: '/app/console'
      path: '/console'
      fullPath: '/app/console'
      preLoaderRoute: typeof AppConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clusters': {
      id: '/app/clusters'
      path: '/clusters'
      fullPath: '/app/clusters'
      preLoaderRoute: typeof AppClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/quota': {
      id: '/app/admin/quota'
      path: '/admin/quota'
      fullPath: '/app/admin/quota'
      preLoaderRoute: typeof AppAdminQuotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/networks': {
      id: '/app/admin/networks'
      path: '/admin/networks'
      fullPath: '/app/admin/networks'
      preLoaderRoute: typeof AppAdminNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/cluster-offerings': {
      id: '/app/admin/cluster-offerings'
      path: '/admin/cluster-offerings'
      fullPath: '/app/admin/cluster-offerings'
      preLoaderRoute: typeof AppAdminClusterOfferingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppClustersRoute: typeof AppClustersRoute
  AppConsoleRoute: typeof AppConsoleRoute
  AppVmsRoute: typeof AppVmsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminClusterOfferingsRoute: typeof AppAdminClusterOfferingsRoute
  AppAdminNetworksRoute: typeof AppAdminNetworksRoute
  AppAdminQuotaRoute: typeof AppAdminQuotaRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppClustersRoute: AppClustersRoute,
  AppConsoleRoute: AppConsoleRoute,
  AppVmsRoute: AppVmsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminClusterOfferingsRoute: AppAdminClusterOfferingsRoute,
  AppAdminNetworksRoute: AppAdminNetworksRoute,
  AppAdminQuotaRoute: AppAdminQuotaRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
