/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVmsRouteImport } from './routes/app.vms'
import { Route as AppConsoleRouteImport } from './routes/app.console'
import { Route as AppClustersRouteImport } from './routes/app.clusters'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppProviderIndexRouteImport } from './routes/app.provider.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppVmsNameRouteImport } from './routes/app.vms.$name'
import { Route as AppProviderTenantsRouteImport } from './routes/app.provider.tenants'
import { Route as AppProviderTemplatesRouteImport } from './routes/app.provider.templates'
import { Route as AppProviderStorageTiersRouteImport } from './routes/app.provider.storage-tiers'
import { Route as AppProviderInfrastructureRouteImport } from './routes/app.provider.infrastructure'
import { Route as AppProviderClustersRouteImport } from './routes/app.provider.clusters'
import { Route as AppProviderAgentsRouteImport } from './routes/app.provider.agents'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminQuotaRouteImport } from './routes/app.admin.quota'
import { Route as AppAdminNetworksRouteImport } from './routes/app.admin.networks'
import { Route as AppAdminClusterOfferingsRouteImport } from './routes/app.admin.cluster-offerings'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVmsRoute = AppVmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleRoute = AppConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersRoute = AppClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderIndexRoute = AppProviderIndexRouteImport.update({
  id: '/provider/',
  path: '/provider/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppVmsNameRoute = AppVmsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppVmsRoute,
} as any)
const AppProviderTenantsRoute = AppProviderTenantsRouteImport.update({
  id: '/provider/tenants',
  path: '/provider/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderTemplatesRoute = AppProviderTemplatesRouteImport.update({
  id: '/provider/templates',
  path: '/provider/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderStorageTiersRoute = AppProviderStorageTiersRouteImport.update({
  id: '/provider/storage-tiers',
  path: '/provider/storage-tiers',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderInfrastructureRoute =
  AppProviderInfrastructureRouteImport.update({
    id: '/provider/infrastructure',
    path: '/provider/infrastructure',
    getParentRoute: () => AppRoute,
  } as any)
const AppProviderClustersRoute = AppProviderClustersRouteImport.update({
  id: '/provider/clusters',
  path: '/provider/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderAgentsRoute = AppProviderAgentsRouteImport.update({
  id: '/provider/agents',
  path: '/provider/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQuotaRoute = AppAdminQuotaRouteImport.update({
  id: '/admin/quota',
  path: '/admin/quota',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNetworksRoute = AppAdminNetworksRouteImport.update({
  id: '/admin/networks',
  path: '/admin/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClusterOfferingsRoute =
  AppAdminClusterOfferingsRouteImport.update({
    id: '/admin/cluster-offerings',
    path: '/admin/cluster-offerings',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRoute
  '/app/console': typeof AppConsoleRoute
  '/app/vms': typeof AppVmsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRoute
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/provider/agents': typeof AppProviderAgentsRoute
  '/app/provider/clusters': typeof AppProviderClustersRoute
  '/app/provider/infrastructure': typeof AppProviderInfrastructureRoute
  '/app/provider/storage-tiers': typeof AppProviderStorageTiersRoute
  '/app/provider/templates': typeof AppProviderTemplatesRoute
  '/app/provider/tenants': typeof AppProviderTenantsRoute
  '/app/vms/$name': typeof AppVmsNameRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/provider/': typeof AppProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRoute
  '/app/console': typeof AppConsoleRoute
  '/app/vms': typeof AppVmsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRoute
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/provider/agents': typeof AppProviderAgentsRoute
  '/app/provider/clusters': typeof AppProviderClustersRoute
  '/app/provider/infrastructure': typeof AppProviderInfrastructureRoute
  '/app/provider/storage-tiers': typeof AppProviderStorageTiersRoute
  '/app/provider/templates': typeof AppProviderTemplatesRoute
  '/app/provider/tenants': typeof AppProviderTenantsRoute
  '/app/vms/$name': typeof AppVmsNameRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/provider': typeof AppProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRoute
  '/app/console': typeof AppConsoleRoute
  '/app/vms': typeof AppVmsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRoute
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/provider/agents': typeof AppProviderAgentsRoute
  '/app/provider/clusters': typeof AppProviderClustersRoute
  '/app/provider/infrastructure': typeof AppProviderInfrastructureRoute
  '/app/provider/storage-tiers': typeof AppProviderStorageTiersRoute
  '/app/provider/templates': typeof AppProviderTemplatesRoute
  '/app/provider/tenants': typeof AppProviderTenantsRoute
  '/app/vms/$name': typeof AppVmsNameRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/provider/': typeof AppProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/activity'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/vms'
    | '/app/'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/provider/agents'
    | '/app/provider/clusters'
    | '/app/provider/infrastructure'
    | '/app/provider/storage-tiers'
    | '/app/provider/templates'
    | '/app/provider/tenants'
    | '/app/vms/$name'
    | '/app/admin/'
    | '/app/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/activity'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/vms'
    | '/app'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/provider/agents'
    | '/app/provider/clusters'
    | '/app/provider/infrastructure'
    | '/app/provider/storage-tiers'
    | '/app/provider/templates'
    | '/app/provider/tenants'
    | '/app/vms/$name'
    | '/app/admin'
    | '/app/provider'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/activity'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/vms'
    | '/app/'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/provider/agents'
    | '/app/provider/clusters'
    | '/app/provider/infrastructure'
    | '/app/provider/storage-tiers'
    | '/app/provider/templates'
    | '/app/provider/tenants'
    | '/app/vms/$name'
    | '/app/admin/'
    | '/app/provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vms': {
      id: '/app/vms'
      path: '/vms'
      fullPath: '/app/vms'
      preLoaderRoute: typeof AppVmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/console': {
      id: '/app/console'
      path: '/console'
      fullPath: '/app/console'
      preLoaderRoute: typeof AppConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clusters': {
      id: '/app/clusters'
      path: '/clusters'
      fullPath: '/app/clusters'
      preLoaderRoute: typeof AppClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/': {
      id: '/app/provider/'
      path: '/provider'
      fullPath: '/app/provider/'
      preLoaderRoute: typeof AppProviderIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vms/$name': {
      id: '/app/vms/$name'
      path: '/$name'
      fullPath: '/app/vms/$name'
      preLoaderRoute: typeof AppVmsNameRouteImport
      parentRoute: typeof AppVmsRoute
    }
    '/app/provider/tenants': {
      id: '/app/provider/tenants'
      path: '/provider/tenants'
      fullPath: '/app/provider/tenants'
      preLoaderRoute: typeof AppProviderTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/templates': {
      id: '/app/provider/templates'
      path: '/provider/templates'
      fullPath: '/app/provider/templates'
      preLoaderRoute: typeof AppProviderTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/storage-tiers': {
      id: '/app/provider/storage-tiers'
      path: '/provider/storage-tiers'
      fullPath: '/app/provider/storage-tiers'
      preLoaderRoute: typeof AppProviderStorageTiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/infrastructure': {
      id: '/app/provider/infrastructure'
      path: '/provider/infrastructure'
      fullPath: '/app/provider/infrastructure'
      preLoaderRoute: typeof AppProviderInfrastructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/clusters': {
      id: '/app/provider/clusters'
      path: '/provider/clusters'
      fullPath: '/app/provider/clusters'
      preLoaderRoute: typeof AppProviderClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/agents': {
      id: '/app/provider/agents'
      path: '/provider/agents'
      fullPath: '/app/provider/agents'
      preLoaderRoute: typeof AppProviderAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/quota': {
      id: '/app/admin/quota'
      path: '/admin/quota'
      fullPath: '/app/admin/quota'
      preLoaderRoute: typeof AppAdminQuotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/networks': {
      id: '/app/admin/networks'
      path: '/admin/networks'
      fullPath: '/app/admin/networks'
      preLoaderRoute: typeof AppAdminNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/cluster-offerings': {
      id: '/app/admin/cluster-offerings'
      path: '/admin/cluster-offerings'
      fullPath: '/app/admin/cluster-offerings'
      preLoaderRoute: typeof AppAdminClusterOfferingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppVmsRouteChildren {
  AppVmsNameRoute: typeof AppVmsNameRoute
}

const AppVmsRouteChildren: AppVmsRouteChildren = {
  AppVmsNameRoute: AppVmsNameRoute,
}

const AppVmsRouteWithChildren =
  AppVmsRoute._addFileChildren(AppVmsRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppClustersRoute: typeof AppClustersRoute
  AppConsoleRoute: typeof AppConsoleRoute
  AppVmsRoute: typeof AppVmsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminClusterOfferingsRoute: typeof AppAdminClusterOfferingsRoute
  AppAdminNetworksRoute: typeof AppAdminNetworksRoute
  AppAdminQuotaRoute: typeof AppAdminQuotaRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppProviderAgentsRoute: typeof AppProviderAgentsRoute
  AppProviderClustersRoute: typeof AppProviderClustersRoute
  AppProviderInfrastructureRoute: typeof AppProviderInfrastructureRoute
  AppProviderStorageTiersRoute: typeof AppProviderStorageTiersRoute
  AppProviderTemplatesRoute: typeof AppProviderTemplatesRoute
  AppProviderTenantsRoute: typeof AppProviderTenantsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppProviderIndexRoute: typeof AppProviderIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppClustersRoute: AppClustersRoute,
  AppConsoleRoute: AppConsoleRoute,
  AppVmsRoute: AppVmsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminClusterOfferingsRoute: AppAdminClusterOfferingsRoute,
  AppAdminNetworksRoute: AppAdminNetworksRoute,
  AppAdminQuotaRoute: AppAdminQuotaRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppProviderAgentsRoute: AppProviderAgentsRoute,
  AppProviderClustersRoute: AppProviderClustersRoute,
  AppProviderInfrastructureRoute: AppProviderInfrastructureRoute,
  AppProviderStorageTiersRoute: AppProviderStorageTiersRoute,
  AppProviderTemplatesRoute: AppProviderTemplatesRoute,
  AppProviderTenantsRoute: AppProviderTenantsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppProviderIndexRoute: AppProviderIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
