/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVmsRouteImport } from './routes/app.vms'
import { Route as AppPublicIpsRouteImport } from './routes/app.public-ips'
import { Route as AppConsoleRouteImport } from './routes/app.console'
import { Route as AppClustersRouteImport } from './routes/app.clusters'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppBareMetalRouteImport } from './routes/app.bare-metal'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppVmsIndexRouteImport } from './routes/app.vms.index'
import { Route as AppProviderIndexRouteImport } from './routes/app.provider.index'
import { Route as AppClustersIndexRouteImport } from './routes/app.clusters.index'
import { Route as AppBareMetalIndexRouteImport } from './routes/app.bare-metal.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppVmsNameRouteImport } from './routes/app.vms.$name'
import { Route as AppProviderVmsRouteImport } from './routes/app.provider.vms'
import { Route as AppProviderTenantsRouteImport } from './routes/app.provider.tenants'
import { Route as AppProviderTemplatesRouteImport } from './routes/app.provider.templates'
import { Route as AppProviderStorageTiersRouteImport } from './routes/app.provider.storage-tiers'
import { Route as AppProviderRbacRouteImport } from './routes/app.provider.rbac'
import { Route as AppProviderPublicIpPoolsRouteImport } from './routes/app.provider.public-ip-pools'
import { Route as AppProviderOrganizationsRouteImport } from './routes/app.provider.organizations'
import { Route as AppProviderOnboardingRouteImport } from './routes/app.provider.onboarding'
import { Route as AppProviderInfrastructureRouteImport } from './routes/app.provider.infrastructure'
import { Route as AppProviderClustersRouteImport } from './routes/app.provider.clusters'
import { Route as AppProviderCatalogItemsRouteImport } from './routes/app.provider.catalog-items'
import { Route as AppProviderBareMetalRouteImport } from './routes/app.provider.bare-metal'
import { Route as AppProviderAnsibleRouteImport } from './routes/app.provider.ansible'
import { Route as AppProviderAgentsRouteImport } from './routes/app.provider.agents'
import { Route as AppClustersNameRouteImport } from './routes/app.clusters.$name'
import { Route as AppBareMetalNameRouteImport } from './routes/app.bare-metal.$name'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminQuotaRouteImport } from './routes/app.admin.quota'
import { Route as AppAdminPublicIpPoolsRouteImport } from './routes/app.admin.public-ip-pools'
import { Route as AppAdminNetworksRouteImport } from './routes/app.admin.networks'
import { Route as AppAdminClusterOfferingsRouteImport } from './routes/app.admin.cluster-offerings'
import { Route as AppProviderTenantsIndexRouteImport } from './routes/app.provider.tenants.index'
import { Route as AppProviderStorageTiersIndexRouteImport } from './routes/app.provider.storage-tiers.index'
import { Route as AppProviderPublicIpPoolsIndexRouteImport } from './routes/app.provider.public-ip-pools.index'
import { Route as AppProviderBareMetalIndexRouteImport } from './routes/app.provider.bare-metal.index'
import { Route as AppProviderAgentsIndexRouteImport } from './routes/app.provider.agents.index'
import { Route as AppAdminPublicIpPoolsIndexRouteImport } from './routes/app.admin.public-ip-pools.index'
import { Route as AppAdminClusterOfferingsIndexRouteImport } from './routes/app.admin.cluster-offerings.index'
import { Route as AppProviderTenantsIdRouteImport } from './routes/app.provider.tenants.$id'
import { Route as AppProviderStorageTiersIdRouteImport } from './routes/app.provider.storage-tiers.$id'
import { Route as AppProviderPublicIpPoolsIdRouteImport } from './routes/app.provider.public-ip-pools.$id'
import { Route as AppProviderBareMetalIdRouteImport } from './routes/app.provider.bare-metal.$id'
import { Route as AppProviderAgentsHostRouteImport } from './routes/app.provider.agents.$host'
import { Route as AppAdminPublicIpPoolsIdRouteImport } from './routes/app.admin.public-ip-pools.$id'
import { Route as AppAdminClusterOfferingsIdRouteImport } from './routes/app.admin.cluster-offerings.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVmsRoute = AppVmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicIpsRoute = AppPublicIpsRouteImport.update({
  id: '/public-ips',
  path: '/public-ips',
  getParentRoute: () => AppRoute,
} as any)
const AppConsoleRoute = AppConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersRoute = AppClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppBareMetalRoute = AppBareMetalRouteImport.update({
  id: '/bare-metal',
  path: '/bare-metal',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppVmsIndexRoute = AppVmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVmsRoute,
} as any)
const AppProviderIndexRoute = AppProviderIndexRouteImport.update({
  id: '/provider/',
  path: '/provider/',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersIndexRoute = AppClustersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClustersRoute,
} as any)
const AppBareMetalIndexRoute = AppBareMetalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBareMetalRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppVmsNameRoute = AppVmsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppVmsRoute,
} as any)
const AppProviderVmsRoute = AppProviderVmsRouteImport.update({
  id: '/provider/vms',
  path: '/provider/vms',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderTenantsRoute = AppProviderTenantsRouteImport.update({
  id: '/provider/tenants',
  path: '/provider/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderTemplatesRoute = AppProviderTemplatesRouteImport.update({
  id: '/provider/templates',
  path: '/provider/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderStorageTiersRoute = AppProviderStorageTiersRouteImport.update({
  id: '/provider/storage-tiers',
  path: '/provider/storage-tiers',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderRbacRoute = AppProviderRbacRouteImport.update({
  id: '/provider/rbac',
  path: '/provider/rbac',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderPublicIpPoolsRoute =
  AppProviderPublicIpPoolsRouteImport.update({
    id: '/provider/public-ip-pools',
    path: '/provider/public-ip-pools',
    getParentRoute: () => AppRoute,
  } as any)
const AppProviderOrganizationsRoute =
  AppProviderOrganizationsRouteImport.update({
    id: '/provider/organizations',
    path: '/provider/organizations',
    getParentRoute: () => AppRoute,
  } as any)
const AppProviderOnboardingRoute = AppProviderOnboardingRouteImport.update({
  id: '/provider/onboarding',
  path: '/provider/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderInfrastructureRoute =
  AppProviderInfrastructureRouteImport.update({
    id: '/provider/infrastructure',
    path: '/provider/infrastructure',
    getParentRoute: () => AppRoute,
  } as any)
const AppProviderClustersRoute = AppProviderClustersRouteImport.update({
  id: '/provider/clusters',
  path: '/provider/clusters',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderCatalogItemsRoute = AppProviderCatalogItemsRouteImport.update({
  id: '/provider/catalog-items',
  path: '/provider/catalog-items',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderBareMetalRoute = AppProviderBareMetalRouteImport.update({
  id: '/provider/bare-metal',
  path: '/provider/bare-metal',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderAnsibleRoute = AppProviderAnsibleRouteImport.update({
  id: '/provider/ansible',
  path: '/provider/ansible',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderAgentsRoute = AppProviderAgentsRouteImport.update({
  id: '/provider/agents',
  path: '/provider/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppClustersNameRoute = AppClustersNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppClustersRoute,
} as any)
const AppBareMetalNameRoute = AppBareMetalNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppBareMetalRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminQuotaRoute = AppAdminQuotaRouteImport.update({
  id: '/admin/quota',
  path: '/admin/quota',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPublicIpPoolsRoute = AppAdminPublicIpPoolsRouteImport.update({
  id: '/admin/public-ip-pools',
  path: '/admin/public-ip-pools',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNetworksRoute = AppAdminNetworksRouteImport.update({
  id: '/admin/networks',
  path: '/admin/networks',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminClusterOfferingsRoute =
  AppAdminClusterOfferingsRouteImport.update({
    id: '/admin/cluster-offerings',
    path: '/admin/cluster-offerings',
    getParentRoute: () => AppRoute,
  } as any)
const AppProviderTenantsIndexRoute = AppProviderTenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProviderTenantsRoute,
} as any)
const AppProviderStorageTiersIndexRoute =
  AppProviderStorageTiersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProviderStorageTiersRoute,
  } as any)
const AppProviderPublicIpPoolsIndexRoute =
  AppProviderPublicIpPoolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProviderPublicIpPoolsRoute,
  } as any)
const AppProviderBareMetalIndexRoute =
  AppProviderBareMetalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProviderBareMetalRoute,
  } as any)
const AppProviderAgentsIndexRoute = AppProviderAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProviderAgentsRoute,
} as any)
const AppAdminPublicIpPoolsIndexRoute =
  AppAdminPublicIpPoolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAdminPublicIpPoolsRoute,
  } as any)
const AppAdminClusterOfferingsIndexRoute =
  AppAdminClusterOfferingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAdminClusterOfferingsRoute,
  } as any)
const AppProviderTenantsIdRoute = AppProviderTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProviderTenantsRoute,
} as any)
const AppProviderStorageTiersIdRoute =
  AppProviderStorageTiersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppProviderStorageTiersRoute,
  } as any)
const AppProviderPublicIpPoolsIdRoute =
  AppProviderPublicIpPoolsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppProviderPublicIpPoolsRoute,
  } as any)
const AppProviderBareMetalIdRoute = AppProviderBareMetalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProviderBareMetalRoute,
} as any)
const AppProviderAgentsHostRoute = AppProviderAgentsHostRouteImport.update({
  id: '/$host',
  path: '/$host',
  getParentRoute: () => AppProviderAgentsRoute,
} as any)
const AppAdminPublicIpPoolsIdRoute = AppAdminPublicIpPoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminPublicIpPoolsRoute,
} as any)
const AppAdminClusterOfferingsIdRoute =
  AppAdminClusterOfferingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppAdminClusterOfferingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/bare-metal': typeof AppBareMetalRouteWithChildren
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRouteWithChildren
  '/app/console': typeof AppConsoleRoute
  '/app/public-ips': typeof AppPublicIpsRoute
  '/app/vms': typeof AppVmsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRouteWithChildren
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/public-ip-pools': typeof AppAdminPublicIpPoolsRouteWithChildren
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/bare-metal/$name': typeof AppBareMetalNameRoute
  '/app/clusters/$name': typeof AppClustersNameRoute
  '/app/provider/agents': typeof AppProviderAgentsRouteWithChildren
  '/app/provider/ansible': typeof AppProviderAnsibleRoute
  '/app/provider/bare-metal': typeof AppProviderBareMetalRouteWithChildren
  '/app/provider/catalog-items': typeof AppProviderCatalogItemsRoute
  '/app/provider/clusters': typeof AppProviderClustersRoute
  '/app/provider/infrastructure': typeof AppProviderInfrastructureRoute
  '/app/provider/onboarding': typeof AppProviderOnboardingRoute
  '/app/provider/organizations': typeof AppProviderOrganizationsRoute
  '/app/provider/public-ip-pools': typeof AppProviderPublicIpPoolsRouteWithChildren
  '/app/provider/rbac': typeof AppProviderRbacRoute
  '/app/provider/storage-tiers': typeof AppProviderStorageTiersRouteWithChildren
  '/app/provider/templates': typeof AppProviderTemplatesRoute
  '/app/provider/tenants': typeof AppProviderTenantsRouteWithChildren
  '/app/provider/vms': typeof AppProviderVmsRoute
  '/app/vms/$name': typeof AppVmsNameRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/bare-metal/': typeof AppBareMetalIndexRoute
  '/app/clusters/': typeof AppClustersIndexRoute
  '/app/provider/': typeof AppProviderIndexRoute
  '/app/vms/': typeof AppVmsIndexRoute
  '/app/admin/cluster-offerings/$id': typeof AppAdminClusterOfferingsIdRoute
  '/app/admin/public-ip-pools/$id': typeof AppAdminPublicIpPoolsIdRoute
  '/app/provider/agents/$host': typeof AppProviderAgentsHostRoute
  '/app/provider/bare-metal/$id': typeof AppProviderBareMetalIdRoute
  '/app/provider/public-ip-pools/$id': typeof AppProviderPublicIpPoolsIdRoute
  '/app/provider/storage-tiers/$id': typeof AppProviderStorageTiersIdRoute
  '/app/provider/tenants/$id': typeof AppProviderTenantsIdRoute
  '/app/admin/cluster-offerings/': typeof AppAdminClusterOfferingsIndexRoute
  '/app/admin/public-ip-pools/': typeof AppAdminPublicIpPoolsIndexRoute
  '/app/provider/agents/': typeof AppProviderAgentsIndexRoute
  '/app/provider/bare-metal/': typeof AppProviderBareMetalIndexRoute
  '/app/provider/public-ip-pools/': typeof AppProviderPublicIpPoolsIndexRoute
  '/app/provider/storage-tiers/': typeof AppProviderStorageTiersIndexRoute
  '/app/provider/tenants/': typeof AppProviderTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/console': typeof AppConsoleRoute
  '/app/public-ips': typeof AppPublicIpsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/bare-metal/$name': typeof AppBareMetalNameRoute
  '/app/clusters/$name': typeof AppClustersNameRoute
  '/app/provider/ansible': typeof AppProviderAnsibleRoute
  '/app/provider/catalog-items': typeof AppProviderCatalogItemsRoute
  '/app/provider/clusters': typeof AppProviderClustersRoute
  '/app/provider/infrastructure': typeof AppProviderInfrastructureRoute
  '/app/provider/onboarding': typeof AppProviderOnboardingRoute
  '/app/provider/organizations': typeof AppProviderOrganizationsRoute
  '/app/provider/rbac': typeof AppProviderRbacRoute
  '/app/provider/templates': typeof AppProviderTemplatesRoute
  '/app/provider/vms': typeof AppProviderVmsRoute
  '/app/vms/$name': typeof AppVmsNameRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/bare-metal': typeof AppBareMetalIndexRoute
  '/app/clusters': typeof AppClustersIndexRoute
  '/app/provider': typeof AppProviderIndexRoute
  '/app/vms': typeof AppVmsIndexRoute
  '/app/admin/cluster-offerings/$id': typeof AppAdminClusterOfferingsIdRoute
  '/app/admin/public-ip-pools/$id': typeof AppAdminPublicIpPoolsIdRoute
  '/app/provider/agents/$host': typeof AppProviderAgentsHostRoute
  '/app/provider/bare-metal/$id': typeof AppProviderBareMetalIdRoute
  '/app/provider/public-ip-pools/$id': typeof AppProviderPublicIpPoolsIdRoute
  '/app/provider/storage-tiers/$id': typeof AppProviderStorageTiersIdRoute
  '/app/provider/tenants/$id': typeof AppProviderTenantsIdRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsIndexRoute
  '/app/admin/public-ip-pools': typeof AppAdminPublicIpPoolsIndexRoute
  '/app/provider/agents': typeof AppProviderAgentsIndexRoute
  '/app/provider/bare-metal': typeof AppProviderBareMetalIndexRoute
  '/app/provider/public-ip-pools': typeof AppProviderPublicIpPoolsIndexRoute
  '/app/provider/storage-tiers': typeof AppProviderStorageTiersIndexRoute
  '/app/provider/tenants': typeof AppProviderTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/app/activity': typeof AppActivityRoute
  '/app/bare-metal': typeof AppBareMetalRouteWithChildren
  '/app/catalog': typeof AppCatalogRoute
  '/app/clusters': typeof AppClustersRouteWithChildren
  '/app/console': typeof AppConsoleRoute
  '/app/public-ips': typeof AppPublicIpsRoute
  '/app/vms': typeof AppVmsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/cluster-offerings': typeof AppAdminClusterOfferingsRouteWithChildren
  '/app/admin/networks': typeof AppAdminNetworksRoute
  '/app/admin/public-ip-pools': typeof AppAdminPublicIpPoolsRouteWithChildren
  '/app/admin/quota': typeof AppAdminQuotaRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/bare-metal/$name': typeof AppBareMetalNameRoute
  '/app/clusters/$name': typeof AppClustersNameRoute
  '/app/provider/agents': typeof AppProviderAgentsRouteWithChildren
  '/app/provider/ansible': typeof AppProviderAnsibleRoute
  '/app/provider/bare-metal': typeof AppProviderBareMetalRouteWithChildren
  '/app/provider/catalog-items': typeof AppProviderCatalogItemsRoute
  '/app/provider/clusters': typeof AppProviderClustersRoute
  '/app/provider/infrastructure': typeof AppProviderInfrastructureRoute
  '/app/provider/onboarding': typeof AppProviderOnboardingRoute
  '/app/provider/organizations': typeof AppProviderOrganizationsRoute
  '/app/provider/public-ip-pools': typeof AppProviderPublicIpPoolsRouteWithChildren
  '/app/provider/rbac': typeof AppProviderRbacRoute
  '/app/provider/storage-tiers': typeof AppProviderStorageTiersRouteWithChildren
  '/app/provider/templates': typeof AppProviderTemplatesRoute
  '/app/provider/tenants': typeof AppProviderTenantsRouteWithChildren
  '/app/provider/vms': typeof AppProviderVmsRoute
  '/app/vms/$name': typeof AppVmsNameRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/bare-metal/': typeof AppBareMetalIndexRoute
  '/app/clusters/': typeof AppClustersIndexRoute
  '/app/provider/': typeof AppProviderIndexRoute
  '/app/vms/': typeof AppVmsIndexRoute
  '/app/admin/cluster-offerings/$id': typeof AppAdminClusterOfferingsIdRoute
  '/app/admin/public-ip-pools/$id': typeof AppAdminPublicIpPoolsIdRoute
  '/app/provider/agents/$host': typeof AppProviderAgentsHostRoute
  '/app/provider/bare-metal/$id': typeof AppProviderBareMetalIdRoute
  '/app/provider/public-ip-pools/$id': typeof AppProviderPublicIpPoolsIdRoute
  '/app/provider/storage-tiers/$id': typeof AppProviderStorageTiersIdRoute
  '/app/provider/tenants/$id': typeof AppProviderTenantsIdRoute
  '/app/admin/cluster-offerings/': typeof AppAdminClusterOfferingsIndexRoute
  '/app/admin/public-ip-pools/': typeof AppAdminPublicIpPoolsIndexRoute
  '/app/provider/agents/': typeof AppProviderAgentsIndexRoute
  '/app/provider/bare-metal/': typeof AppProviderBareMetalIndexRoute
  '/app/provider/public-ip-pools/': typeof AppProviderPublicIpPoolsIndexRoute
  '/app/provider/storage-tiers/': typeof AppProviderStorageTiersIndexRoute
  '/app/provider/tenants/': typeof AppProviderTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/activity'
    | '/app/bare-metal'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/public-ips'
    | '/app/vms'
    | '/app/'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/public-ip-pools'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/bare-metal/$name'
    | '/app/clusters/$name'
    | '/app/provider/agents'
    | '/app/provider/ansible'
    | '/app/provider/bare-metal'
    | '/app/provider/catalog-items'
    | '/app/provider/clusters'
    | '/app/provider/infrastructure'
    | '/app/provider/onboarding'
    | '/app/provider/organizations'
    | '/app/provider/public-ip-pools'
    | '/app/provider/rbac'
    | '/app/provider/storage-tiers'
    | '/app/provider/templates'
    | '/app/provider/tenants'
    | '/app/provider/vms'
    | '/app/vms/$name'
    | '/app/admin/'
    | '/app/bare-metal/'
    | '/app/clusters/'
    | '/app/provider/'
    | '/app/vms/'
    | '/app/admin/cluster-offerings/$id'
    | '/app/admin/public-ip-pools/$id'
    | '/app/provider/agents/$host'
    | '/app/provider/bare-metal/$id'
    | '/app/provider/public-ip-pools/$id'
    | '/app/provider/storage-tiers/$id'
    | '/app/provider/tenants/$id'
    | '/app/admin/cluster-offerings/'
    | '/app/admin/public-ip-pools/'
    | '/app/provider/agents/'
    | '/app/provider/bare-metal/'
    | '/app/provider/public-ip-pools/'
    | '/app/provider/storage-tiers/'
    | '/app/provider/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/app/activity'
    | '/app/catalog'
    | '/app/console'
    | '/app/public-ips'
    | '/app'
    | '/app/admin/networks'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/bare-metal/$name'
    | '/app/clusters/$name'
    | '/app/provider/ansible'
    | '/app/provider/catalog-items'
    | '/app/provider/clusters'
    | '/app/provider/infrastructure'
    | '/app/provider/onboarding'
    | '/app/provider/organizations'
    | '/app/provider/rbac'
    | '/app/provider/templates'
    | '/app/provider/vms'
    | '/app/vms/$name'
    | '/app/admin'
    | '/app/bare-metal'
    | '/app/clusters'
    | '/app/provider'
    | '/app/vms'
    | '/app/admin/cluster-offerings/$id'
    | '/app/admin/public-ip-pools/$id'
    | '/app/provider/agents/$host'
    | '/app/provider/bare-metal/$id'
    | '/app/provider/public-ip-pools/$id'
    | '/app/provider/storage-tiers/$id'
    | '/app/provider/tenants/$id'
    | '/app/admin/cluster-offerings'
    | '/app/admin/public-ip-pools'
    | '/app/provider/agents'
    | '/app/provider/bare-metal'
    | '/app/provider/public-ip-pools'
    | '/app/provider/storage-tiers'
    | '/app/provider/tenants'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/app/activity'
    | '/app/bare-metal'
    | '/app/catalog'
    | '/app/clusters'
    | '/app/console'
    | '/app/public-ips'
    | '/app/vms'
    | '/app/'
    | '/app/admin/cluster-offerings'
    | '/app/admin/networks'
    | '/app/admin/public-ip-pools'
    | '/app/admin/quota'
    | '/app/admin/users'
    | '/app/bare-metal/$name'
    | '/app/clusters/$name'
    | '/app/provider/agents'
    | '/app/provider/ansible'
    | '/app/provider/bare-metal'
    | '/app/provider/catalog-items'
    | '/app/provider/clusters'
    | '/app/provider/infrastructure'
    | '/app/provider/onboarding'
    | '/app/provider/organizations'
    | '/app/provider/public-ip-pools'
    | '/app/provider/rbac'
    | '/app/provider/storage-tiers'
    | '/app/provider/templates'
    | '/app/provider/tenants'
    | '/app/provider/vms'
    | '/app/vms/$name'
    | '/app/admin/'
    | '/app/bare-metal/'
    | '/app/clusters/'
    | '/app/provider/'
    | '/app/vms/'
    | '/app/admin/cluster-offerings/$id'
    | '/app/admin/public-ip-pools/$id'
    | '/app/provider/agents/$host'
    | '/app/provider/bare-metal/$id'
    | '/app/provider/public-ip-pools/$id'
    | '/app/provider/storage-tiers/$id'
    | '/app/provider/tenants/$id'
    | '/app/admin/cluster-offerings/'
    | '/app/admin/public-ip-pools/'
    | '/app/provider/agents/'
    | '/app/provider/bare-metal/'
    | '/app/provider/public-ip-pools/'
    | '/app/provider/storage-tiers/'
    | '/app/provider/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vms': {
      id: '/app/vms'
      path: '/vms'
      fullPath: '/app/vms'
      preLoaderRoute: typeof AppVmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/public-ips': {
      id: '/app/public-ips'
      path: '/public-ips'
      fullPath: '/app/public-ips'
      preLoaderRoute: typeof AppPublicIpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/console': {
      id: '/app/console'
      path: '/console'
      fullPath: '/app/console'
      preLoaderRoute: typeof AppConsoleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clusters': {
      id: '/app/clusters'
      path: '/clusters'
      fullPath: '/app/clusters'
      preLoaderRoute: typeof AppClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bare-metal': {
      id: '/app/bare-metal'
      path: '/bare-metal'
      fullPath: '/app/bare-metal'
      preLoaderRoute: typeof AppBareMetalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vms/': {
      id: '/app/vms/'
      path: '/'
      fullPath: '/app/vms/'
      preLoaderRoute: typeof AppVmsIndexRouteImport
      parentRoute: typeof AppVmsRoute
    }
    '/app/provider/': {
      id: '/app/provider/'
      path: '/provider'
      fullPath: '/app/provider/'
      preLoaderRoute: typeof AppProviderIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clusters/': {
      id: '/app/clusters/'
      path: '/'
      fullPath: '/app/clusters/'
      preLoaderRoute: typeof AppClustersIndexRouteImport
      parentRoute: typeof AppClustersRoute
    }
    '/app/bare-metal/': {
      id: '/app/bare-metal/'
      path: '/'
      fullPath: '/app/bare-metal/'
      preLoaderRoute: typeof AppBareMetalIndexRouteImport
      parentRoute: typeof AppBareMetalRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vms/$name': {
      id: '/app/vms/$name'
      path: '/$name'
      fullPath: '/app/vms/$name'
      preLoaderRoute: typeof AppVmsNameRouteImport
      parentRoute: typeof AppVmsRoute
    }
    '/app/provider/vms': {
      id: '/app/provider/vms'
      path: '/provider/vms'
      fullPath: '/app/provider/vms'
      preLoaderRoute: typeof AppProviderVmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/tenants': {
      id: '/app/provider/tenants'
      path: '/provider/tenants'
      fullPath: '/app/provider/tenants'
      preLoaderRoute: typeof AppProviderTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/templates': {
      id: '/app/provider/templates'
      path: '/provider/templates'
      fullPath: '/app/provider/templates'
      preLoaderRoute: typeof AppProviderTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/storage-tiers': {
      id: '/app/provider/storage-tiers'
      path: '/provider/storage-tiers'
      fullPath: '/app/provider/storage-tiers'
      preLoaderRoute: typeof AppProviderStorageTiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/rbac': {
      id: '/app/provider/rbac'
      path: '/provider/rbac'
      fullPath: '/app/provider/rbac'
      preLoaderRoute: typeof AppProviderRbacRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/public-ip-pools': {
      id: '/app/provider/public-ip-pools'
      path: '/provider/public-ip-pools'
      fullPath: '/app/provider/public-ip-pools'
      preLoaderRoute: typeof AppProviderPublicIpPoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/organizations': {
      id: '/app/provider/organizations'
      path: '/provider/organizations'
      fullPath: '/app/provider/organizations'
      preLoaderRoute: typeof AppProviderOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/onboarding': {
      id: '/app/provider/onboarding'
      path: '/provider/onboarding'
      fullPath: '/app/provider/onboarding'
      preLoaderRoute: typeof AppProviderOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/infrastructure': {
      id: '/app/provider/infrastructure'
      path: '/provider/infrastructure'
      fullPath: '/app/provider/infrastructure'
      preLoaderRoute: typeof AppProviderInfrastructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/clusters': {
      id: '/app/provider/clusters'
      path: '/provider/clusters'
      fullPath: '/app/provider/clusters'
      preLoaderRoute: typeof AppProviderClustersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/catalog-items': {
      id: '/app/provider/catalog-items'
      path: '/provider/catalog-items'
      fullPath: '/app/provider/catalog-items'
      preLoaderRoute: typeof AppProviderCatalogItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/bare-metal': {
      id: '/app/provider/bare-metal'
      path: '/provider/bare-metal'
      fullPath: '/app/provider/bare-metal'
      preLoaderRoute: typeof AppProviderBareMetalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/ansible': {
      id: '/app/provider/ansible'
      path: '/provider/ansible'
      fullPath: '/app/provider/ansible'
      preLoaderRoute: typeof AppProviderAnsibleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/agents': {
      id: '/app/provider/agents'
      path: '/provider/agents'
      fullPath: '/app/provider/agents'
      preLoaderRoute: typeof AppProviderAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clusters/$name': {
      id: '/app/clusters/$name'
      path: '/$name'
      fullPath: '/app/clusters/$name'
      preLoaderRoute: typeof AppClustersNameRouteImport
      parentRoute: typeof AppClustersRoute
    }
    '/app/bare-metal/$name': {
      id: '/app/bare-metal/$name'
      path: '/$name'
      fullPath: '/app/bare-metal/$name'
      preLoaderRoute: typeof AppBareMetalNameRouteImport
      parentRoute: typeof AppBareMetalRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/quota': {
      id: '/app/admin/quota'
      path: '/admin/quota'
      fullPath: '/app/admin/quota'
      preLoaderRoute: typeof AppAdminQuotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/public-ip-pools': {
      id: '/app/admin/public-ip-pools'
      path: '/admin/public-ip-pools'
      fullPath: '/app/admin/public-ip-pools'
      preLoaderRoute: typeof AppAdminPublicIpPoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/networks': {
      id: '/app/admin/networks'
      path: '/admin/networks'
      fullPath: '/app/admin/networks'
      preLoaderRoute: typeof AppAdminNetworksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/cluster-offerings': {
      id: '/app/admin/cluster-offerings'
      path: '/admin/cluster-offerings'
      fullPath: '/app/admin/cluster-offerings'
      preLoaderRoute: typeof AppAdminClusterOfferingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/provider/tenants/': {
      id: '/app/provider/tenants/'
      path: '/'
      fullPath: '/app/provider/tenants/'
      preLoaderRoute: typeof AppProviderTenantsIndexRouteImport
      parentRoute: typeof AppProviderTenantsRoute
    }
    '/app/provider/storage-tiers/': {
      id: '/app/provider/storage-tiers/'
      path: '/'
      fullPath: '/app/provider/storage-tiers/'
      preLoaderRoute: typeof AppProviderStorageTiersIndexRouteImport
      parentRoute: typeof AppProviderStorageTiersRoute
    }
    '/app/provider/public-ip-pools/': {
      id: '/app/provider/public-ip-pools/'
      path: '/'
      fullPath: '/app/provider/public-ip-pools/'
      preLoaderRoute: typeof AppProviderPublicIpPoolsIndexRouteImport
      parentRoute: typeof AppProviderPublicIpPoolsRoute
    }
    '/app/provider/bare-metal/': {
      id: '/app/provider/bare-metal/'
      path: '/'
      fullPath: '/app/provider/bare-metal/'
      preLoaderRoute: typeof AppProviderBareMetalIndexRouteImport
      parentRoute: typeof AppProviderBareMetalRoute
    }
    '/app/provider/agents/': {
      id: '/app/provider/agents/'
      path: '/'
      fullPath: '/app/provider/agents/'
      preLoaderRoute: typeof AppProviderAgentsIndexRouteImport
      parentRoute: typeof AppProviderAgentsRoute
    }
    '/app/admin/public-ip-pools/': {
      id: '/app/admin/public-ip-pools/'
      path: '/'
      fullPath: '/app/admin/public-ip-pools/'
      preLoaderRoute: typeof AppAdminPublicIpPoolsIndexRouteImport
      parentRoute: typeof AppAdminPublicIpPoolsRoute
    }
    '/app/admin/cluster-offerings/': {
      id: '/app/admin/cluster-offerings/'
      path: '/'
      fullPath: '/app/admin/cluster-offerings/'
      preLoaderRoute: typeof AppAdminClusterOfferingsIndexRouteImport
      parentRoute: typeof AppAdminClusterOfferingsRoute
    }
    '/app/provider/tenants/$id': {
      id: '/app/provider/tenants/$id'
      path: '/$id'
      fullPath: '/app/provider/tenants/$id'
      preLoaderRoute: typeof AppProviderTenantsIdRouteImport
      parentRoute: typeof AppProviderTenantsRoute
    }
    '/app/provider/storage-tiers/$id': {
      id: '/app/provider/storage-tiers/$id'
      path: '/$id'
      fullPath: '/app/provider/storage-tiers/$id'
      preLoaderRoute: typeof AppProviderStorageTiersIdRouteImport
      parentRoute: typeof AppProviderStorageTiersRoute
    }
    '/app/provider/public-ip-pools/$id': {
      id: '/app/provider/public-ip-pools/$id'
      path: '/$id'
      fullPath: '/app/provider/public-ip-pools/$id'
      preLoaderRoute: typeof AppProviderPublicIpPoolsIdRouteImport
      parentRoute: typeof AppProviderPublicIpPoolsRoute
    }
    '/app/provider/bare-metal/$id': {
      id: '/app/provider/bare-metal/$id'
      path: '/$id'
      fullPath: '/app/provider/bare-metal/$id'
      preLoaderRoute: typeof AppProviderBareMetalIdRouteImport
      parentRoute: typeof AppProviderBareMetalRoute
    }
    '/app/provider/agents/$host': {
      id: '/app/provider/agents/$host'
      path: '/$host'
      fullPath: '/app/provider/agents/$host'
      preLoaderRoute: typeof AppProviderAgentsHostRouteImport
      parentRoute: typeof AppProviderAgentsRoute
    }
    '/app/admin/public-ip-pools/$id': {
      id: '/app/admin/public-ip-pools/$id'
      path: '/$id'
      fullPath: '/app/admin/public-ip-pools/$id'
      preLoaderRoute: typeof AppAdminPublicIpPoolsIdRouteImport
      parentRoute: typeof AppAdminPublicIpPoolsRoute
    }
    '/app/admin/cluster-offerings/$id': {
      id: '/app/admin/cluster-offerings/$id'
      path: '/$id'
      fullPath: '/app/admin/cluster-offerings/$id'
      preLoaderRoute: typeof AppAdminClusterOfferingsIdRouteImport
      parentRoute: typeof AppAdminClusterOfferingsRoute
    }
  }
}

interface AppBareMetalRouteChildren {
  AppBareMetalNameRoute: typeof AppBareMetalNameRoute
  AppBareMetalIndexRoute: typeof AppBareMetalIndexRoute
}

const AppBareMetalRouteChildren: AppBareMetalRouteChildren = {
  AppBareMetalNameRoute: AppBareMetalNameRoute,
  AppBareMetalIndexRoute: AppBareMetalIndexRoute,
}

const AppBareMetalRouteWithChildren = AppBareMetalRoute._addFileChildren(
  AppBareMetalRouteChildren,
)

interface AppClustersRouteChildren {
  AppClustersNameRoute: typeof AppClustersNameRoute
  AppClustersIndexRoute: typeof AppClustersIndexRoute
}

const AppClustersRouteChildren: AppClustersRouteChildren = {
  AppClustersNameRoute: AppClustersNameRoute,
  AppClustersIndexRoute: AppClustersIndexRoute,
}

const AppClustersRouteWithChildren = AppClustersRoute._addFileChildren(
  AppClustersRouteChildren,
)

interface AppVmsRouteChildren {
  AppVmsNameRoute: typeof AppVmsNameRoute
  AppVmsIndexRoute: typeof AppVmsIndexRoute
}

const AppVmsRouteChildren: AppVmsRouteChildren = {
  AppVmsNameRoute: AppVmsNameRoute,
  AppVmsIndexRoute: AppVmsIndexRoute,
}

const AppVmsRouteWithChildren =
  AppVmsRoute._addFileChildren(AppVmsRouteChildren)

interface AppAdminClusterOfferingsRouteChildren {
  AppAdminClusterOfferingsIdRoute: typeof AppAdminClusterOfferingsIdRoute
  AppAdminClusterOfferingsIndexRoute: typeof AppAdminClusterOfferingsIndexRoute
}

const AppAdminClusterOfferingsRouteChildren: AppAdminClusterOfferingsRouteChildren =
  {
    AppAdminClusterOfferingsIdRoute: AppAdminClusterOfferingsIdRoute,
    AppAdminClusterOfferingsIndexRoute: AppAdminClusterOfferingsIndexRoute,
  }

const AppAdminClusterOfferingsRouteWithChildren =
  AppAdminClusterOfferingsRoute._addFileChildren(
    AppAdminClusterOfferingsRouteChildren,
  )

interface AppAdminPublicIpPoolsRouteChildren {
  AppAdminPublicIpPoolsIdRoute: typeof AppAdminPublicIpPoolsIdRoute
  AppAdminPublicIpPoolsIndexRoute: typeof AppAdminPublicIpPoolsIndexRoute
}

const AppAdminPublicIpPoolsRouteChildren: AppAdminPublicIpPoolsRouteChildren = {
  AppAdminPublicIpPoolsIdRoute: AppAdminPublicIpPoolsIdRoute,
  AppAdminPublicIpPoolsIndexRoute: AppAdminPublicIpPoolsIndexRoute,
}

const AppAdminPublicIpPoolsRouteWithChildren =
  AppAdminPublicIpPoolsRoute._addFileChildren(
    AppAdminPublicIpPoolsRouteChildren,
  )

interface AppProviderAgentsRouteChildren {
  AppProviderAgentsHostRoute: typeof AppProviderAgentsHostRoute
  AppProviderAgentsIndexRoute: typeof AppProviderAgentsIndexRoute
}

const AppProviderAgentsRouteChildren: AppProviderAgentsRouteChildren = {
  AppProviderAgentsHostRoute: AppProviderAgentsHostRoute,
  AppProviderAgentsIndexRoute: AppProviderAgentsIndexRoute,
}

const AppProviderAgentsRouteWithChildren =
  AppProviderAgentsRoute._addFileChildren(AppProviderAgentsRouteChildren)

interface AppProviderBareMetalRouteChildren {
  AppProviderBareMetalIdRoute: typeof AppProviderBareMetalIdRoute
  AppProviderBareMetalIndexRoute: typeof AppProviderBareMetalIndexRoute
}

const AppProviderBareMetalRouteChildren: AppProviderBareMetalRouteChildren = {
  AppProviderBareMetalIdRoute: AppProviderBareMetalIdRoute,
  AppProviderBareMetalIndexRoute: AppProviderBareMetalIndexRoute,
}

const AppProviderBareMetalRouteWithChildren =
  AppProviderBareMetalRoute._addFileChildren(AppProviderBareMetalRouteChildren)

interface AppProviderPublicIpPoolsRouteChildren {
  AppProviderPublicIpPoolsIdRoute: typeof AppProviderPublicIpPoolsIdRoute
  AppProviderPublicIpPoolsIndexRoute: typeof AppProviderPublicIpPoolsIndexRoute
}

const AppProviderPublicIpPoolsRouteChildren: AppProviderPublicIpPoolsRouteChildren =
  {
    AppProviderPublicIpPoolsIdRoute: AppProviderPublicIpPoolsIdRoute,
    AppProviderPublicIpPoolsIndexRoute: AppProviderPublicIpPoolsIndexRoute,
  }

const AppProviderPublicIpPoolsRouteWithChildren =
  AppProviderPublicIpPoolsRoute._addFileChildren(
    AppProviderPublicIpPoolsRouteChildren,
  )

interface AppProviderStorageTiersRouteChildren {
  AppProviderStorageTiersIdRoute: typeof AppProviderStorageTiersIdRoute
  AppProviderStorageTiersIndexRoute: typeof AppProviderStorageTiersIndexRoute
}

const AppProviderStorageTiersRouteChildren: AppProviderStorageTiersRouteChildren =
  {
    AppProviderStorageTiersIdRoute: AppProviderStorageTiersIdRoute,
    AppProviderStorageTiersIndexRoute: AppProviderStorageTiersIndexRoute,
  }

const AppProviderStorageTiersRouteWithChildren =
  AppProviderStorageTiersRoute._addFileChildren(
    AppProviderStorageTiersRouteChildren,
  )

interface AppProviderTenantsRouteChildren {
  AppProviderTenantsIdRoute: typeof AppProviderTenantsIdRoute
  AppProviderTenantsIndexRoute: typeof AppProviderTenantsIndexRoute
}

const AppProviderTenantsRouteChildren: AppProviderTenantsRouteChildren = {
  AppProviderTenantsIdRoute: AppProviderTenantsIdRoute,
  AppProviderTenantsIndexRoute: AppProviderTenantsIndexRoute,
}

const AppProviderTenantsRouteWithChildren =
  AppProviderTenantsRoute._addFileChildren(AppProviderTenantsRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppBareMetalRoute: typeof AppBareMetalRouteWithChildren
  AppCatalogRoute: typeof AppCatalogRoute
  AppClustersRoute: typeof AppClustersRouteWithChildren
  AppConsoleRoute: typeof AppConsoleRoute
  AppPublicIpsRoute: typeof AppPublicIpsRoute
  AppVmsRoute: typeof AppVmsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminClusterOfferingsRoute: typeof AppAdminClusterOfferingsRouteWithChildren
  AppAdminNetworksRoute: typeof AppAdminNetworksRoute
  AppAdminPublicIpPoolsRoute: typeof AppAdminPublicIpPoolsRouteWithChildren
  AppAdminQuotaRoute: typeof AppAdminQuotaRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppProviderAgentsRoute: typeof AppProviderAgentsRouteWithChildren
  AppProviderAnsibleRoute: typeof AppProviderAnsibleRoute
  AppProviderBareMetalRoute: typeof AppProviderBareMetalRouteWithChildren
  AppProviderCatalogItemsRoute: typeof AppProviderCatalogItemsRoute
  AppProviderClustersRoute: typeof AppProviderClustersRoute
  AppProviderInfrastructureRoute: typeof AppProviderInfrastructureRoute
  AppProviderOnboardingRoute: typeof AppProviderOnboardingRoute
  AppProviderOrganizationsRoute: typeof AppProviderOrganizationsRoute
  AppProviderPublicIpPoolsRoute: typeof AppProviderPublicIpPoolsRouteWithChildren
  AppProviderRbacRoute: typeof AppProviderRbacRoute
  AppProviderStorageTiersRoute: typeof AppProviderStorageTiersRouteWithChildren
  AppProviderTemplatesRoute: typeof AppProviderTemplatesRoute
  AppProviderTenantsRoute: typeof AppProviderTenantsRouteWithChildren
  AppProviderVmsRoute: typeof AppProviderVmsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppProviderIndexRoute: typeof AppProviderIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppBareMetalRoute: AppBareMetalRouteWithChildren,
  AppCatalogRoute: AppCatalogRoute,
  AppClustersRoute: AppClustersRouteWithChildren,
  AppConsoleRoute: AppConsoleRoute,
  AppPublicIpsRoute: AppPublicIpsRoute,
  AppVmsRoute: AppVmsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminClusterOfferingsRoute: AppAdminClusterOfferingsRouteWithChildren,
  AppAdminNetworksRoute: AppAdminNetworksRoute,
  AppAdminPublicIpPoolsRoute: AppAdminPublicIpPoolsRouteWithChildren,
  AppAdminQuotaRoute: AppAdminQuotaRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppProviderAgentsRoute: AppProviderAgentsRouteWithChildren,
  AppProviderAnsibleRoute: AppProviderAnsibleRoute,
  AppProviderBareMetalRoute: AppProviderBareMetalRouteWithChildren,
  AppProviderCatalogItemsRoute: AppProviderCatalogItemsRoute,
  AppProviderClustersRoute: AppProviderClustersRoute,
  AppProviderInfrastructureRoute: AppProviderInfrastructureRoute,
  AppProviderOnboardingRoute: AppProviderOnboardingRoute,
  AppProviderOrganizationsRoute: AppProviderOrganizationsRoute,
  AppProviderPublicIpPoolsRoute: AppProviderPublicIpPoolsRouteWithChildren,
  AppProviderRbacRoute: AppProviderRbacRoute,
  AppProviderStorageTiersRoute: AppProviderStorageTiersRouteWithChildren,
  AppProviderTemplatesRoute: AppProviderTemplatesRoute,
  AppProviderTenantsRoute: AppProviderTenantsRouteWithChildren,
  AppProviderVmsRoute: AppProviderVmsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppProviderIndexRoute: AppProviderIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
